/datum/asset/simple/inventory
	assets = list(
		"inventory-glasses.png"      = 'icons/runtime/assets/inventory/glasses.png',
		"inventory-head.png"         = 'icons/runtime/assets/inventory/head.png',
		"inventory-neck.png"         = 'icons/runtime/assets/inventory/neck.png',
		"inventory-mask.png"         = 'icons/runtime/assets/inventory/mask.png',
		"inventory-ears.png"         = 'icons/runtime/assets/inventory/ears.png',
		"inventory-uniform.png"      = 'icons/runtime/assets/inventory/uniform.png',
		"inventory-suit.png"         = 'icons/runtime/assets/inventory/suit.png',
		"inventory-gloves.png"       = 'icons/runtime/assets/inventory/gloves.png',
		"inventory-hand_l.png"       = 'icons/runtime/assets/inventory/hand_l.png',
		"inventory-hand_r.png"       = 'icons/runtime/assets/inventory/hand_r.png',
		"inventory-shoes.png"        = 'icons/runtime/assets/inventory/shoes.png',
		"inventory-suit_storage.png" = 'icons/runtime/assets/inventory/suit_storage.png',
		"inventory-id.png"           = 'icons/runtime/assets/inventory/id.png',
		"inventory-belt.png"         = 'icons/runtime/assets/inventory/belt.png',
		"inventory-back.png"         = 'icons/runtime/assets/inventory/back.png',
		"inventory-pocket.png"       = 'icons/runtime/assets/inventory/pocket.png',
		"inventory-collar.png"       = 'icons/runtime/assets/inventory/collar.png',
	)
